### PR TITLE
added new example grafana dashboard with latest panels

### PR DESCRIPTION
**Pull request by scMarkus**
Grafana released a new version with some new panels. This example dashboard is build using these panels.

### CODE REVIEW

**Comment by 0xERR0R** [comment]
Thank you! Is it the dashboard as described in #16?

**Comment by scMarkus** [comment]
yes it is, I simply confused my github accounts last night^^

**Comment by 0xERR0R** [comment]
Ok, may I use your screenshots from the issue to link the JSON in the readme file?

**Comment by scMarkus** [comment]
I did a slight reorder and rename. So pleas take this one:

image

**Pull request merged**
